services:
  polly-memo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polly-memo-fastapi
    ports:
      - "9000:9000"
    env_file:
      - .env  # 从根目录的.env文件读取环境变量
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # 临时文件存储
      - temp_media:/tmp/media_processing
    networks:
      - polly-memo-network

volumes:
  # 临时媒体文件存储
  temp_media:
    driver: local

networks:
  polly-memo-network:
    driver: bridge 