services:
  # 主应用服务
  polly-memo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polly-memo-api
    restart: unless-stopped
    ports:
      - "8000:8000"  # 直接暴露8000端口给宝塔nginx代理
    environment:
      # Supabase配置
      - SUPABASE_URL=${SUPABASE_URL:-https://zodrgxcwimdhuqhdmehg.supabase.co}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_BUCKET_NAME=${SUPABASE_BUCKET_NAME:-polly_memo}
      
      # 文件处理配置
      - MAX_FILE_SIZE=${MAX_FILE_SIZE:-104857600}  # 100MB
      - TARGET_FILE_SIZE=${TARGET_FILE_SIZE:-10485760}  # 10MB
      - TEMP_DIR=${TEMP_DIR:-/tmp/media_processing}
      
      # ASR配置 - 使用新的Whisper API
      # - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}  # 不再需要
      # - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}    # 不再需要 
      # - ASR_API_BASE_URL=${ASR_API_BASE_URL:-https://api.cloudflare.com/client/v4/accounts}  # 旧版API
      - WHISPER_API_URL=${WHISPER_API_URL:-https://whisper-large-v3-turbo.pollylearn.com}
      - ASR_MODEL=${ASR_MODEL:-whisper-large-v3-turbo}
      - ASR_DEFAULT_LANGUAGE=${ASR_DEFAULT_LANGUAGE:-en}
      
      # GLM-4配置
      - GLM4_API_KEY=${GLM4_API_KEY}
      - GLM4_BASE_URL=${GLM4_BASE_URL:-https://open.bigmodel.cn/api/paas/v4}
      - GLM4_MODEL=${GLM4_MODEL:-glm-4-flash}
      - GLM4_TIMEOUT=${GLM4_TIMEOUT:-60}
      - GLM4_MAX_TOKENS=${GLM4_MAX_TOKENS:-4096}
    volumes:
      # 临时文件存储
      - temp_media:/tmp/media_processing
    networks:
      - polly-memo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  # 临时媒体文件存储
  temp_media:
    driver: local

networks:
  polly-memo-network:
    driver: bridge 