version: '3.8'

services:
  polly-memo-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: polly-memo-fastapi
    ports:
      - "9000:9000"
    env_file:
      - .env  # 从根目录的.env文件读取环境变量
    volumes:
      # 可选：挂载日志目录
      - "./logs:/app/logs"
      # 可选：挂载临时处理目录（用于调试）
      - "./temp:/tmp/media_processing"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - polly-memo-network

# 可选：如果需要添加其他服务（如数据库、Redis等）
# services:
#   redis:
#     image: redis:7-alpine
#     container_name: polly-memo-redis
#     ports:
#       - "6379:6379"
#     networks:
#       - polly-memo-network

networks:
  polly-memo-network:
    driver: bridge 